---

- name: install haproxy
  apt:
    name:
      - haproxy

- name: haproxy config
  template:
    src: 'haproxy.cfg.j2'
    dest: '/etc/haproxy/haproxy.cfg'
    owner: root
    group: root

- name: haproxy service
  service:
    name: haproxy
    state: restarted
    enabled: yes
